<a href="https://colab.research.google.com/github/ZaietsMykytaFIT/CH_M_Zaiets/blob/main/Lab4MykytaZaiets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 4, усюди варіанти 3

In [100]:
import numpy as np

Завдання 1: Знайти матрицю С = 𝐴𝐵−𝐵𝐴

In [101]:
matrix_A = np.matrix('1 1 1; 0 1 1; 0 0 1')
matrix_B = np.matrix('7 5 3; 0 7 5; 0 0 7')

matrix_C = np.dot(matrix_A, matrix_B) - np.dot(matrix_B, matrix_A)

print (matrix_C)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Завдання 2: Піднести матриці до степеня

In [102]:
matrix_A = np.matrix('5 0 0 0; 0 -2 0 0; 0 0 3 0; 0 0 0 2')

matrix_F = matrix_A.dot(matrix_A)

print(matrix_F)

[[25  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0  4]]


Завдання 3: Знайти добуток матриць

In [103]:
matrix_A = np.matrix('3 0 7; -4 2 3; -1 1 2')
matrix_B = np.matrix('1; 2; 4')

matrix_F = np.dot(matrix_A, matrix_B)

print(matrix_F)

[[31]
 [12]
 [ 9]]


Завдання 4: Обчислити визначники

In [104]:
matrix_A = np.matrix('2 4 5; 1 1 2; 2 4 3')

matrix_A_det = np.linalg.det(matrix_A)

print (matrix_A_det)

4.0


Завдання 5: Обчислити визначники

In [105]:
matrix_A = np.matrix('1 2 0 0 0; 1 0 2 0 0; 1 0 0 2 0; 1 0 0 0 2; 0 0 1 1 1')

matrix_A_det = round(np.linalg.det(matrix_A), 12)

print (matrix_A_det)

-24.0


Завдання 6: Знайти обернену матрицю до матриць


In [106]:
matrix_A = np.matrix('1 2 2; 2 1 -2; 2 -2 1')

matrix_A_inv = np.linalg.inv(matrix_A)

print(matrix_A_inv)

[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


Завдання 7: Визначити ранг матриці

In [107]:
matrix_A = np.matrix('-2 3 1 -1; 3 2 1 4; 1 2 3 4; 0 2 3 3')

matrix_A_rank = np.linalg.matrix_rank(matrix_A)

print(matrix_A_rank)

3


Завдання 8: Розв’язати систему лінійних рівнянь методом Крамера, матричним методом (тобто обчислити обернену матрицю) і м. Гауса. Потім зробити перевірку за допомогою solve() пакету linalg

In [108]:
def cramer_method(var, const):
    det_var = np.linalg.det(var)
    solutions = []
    for i in range(len(var)):
        modified_var = np.matrix(var)
        modified_var[:, i] = const
        solutions.append(round(np.linalg.det(modified_var) / det_var, 12))
    return solutions

def matrix_method(var, const):
    inv_matrix = np.linalg.inv(var)
    return np.dot(inv_matrix, const)

def gauss_method(a, b): # Ідеї як прибрати попередження - відсутні
    n = len(b)

    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]

    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]

    return x

left_side = np.matrix('3 -5 3; 1 2 1; 2 7 -1')
right_side = np.matrix('1; 4; 8')


print("Cramer method - ", cramer_method(left_side, right_side))
print("Matrix_method - ", matrix_method(left_side, right_side).T)
print("Gauss_method - ", gauss_method(left_side, right_side))

Cramer method -  [1.0, 1.0, 1.0]
Matrix_method -  [[1. 1. 1.]]
Gauss_method -  [1. 1. 1.]


<ipython-input-108-1305aa523443>:26: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]


Пункт 2: Створіть прямокутну матрицю A, яка має N рядків і M стовпців з випадковими елементами. Визначте середні значення для всіх рядків і стовпців матриці.

In [109]:
import random as rnd

def rndMatrix():
  n = rnd.randint(2, 6)
  m = rnd.randint(2, 6)
  arr = np.zeros((n,m), dtype=int)
  for i in range(n):
    for j in range(m):
     arr[i][j]=(rnd.randint(-99, 99))
  return arr

def avgRow(a):
  row = []
  rows = len(a)
  for i in range(0, rows):
    row.append(round(np.average(a[i]), 3))
  return (row)

def avgColumn(a):
  column = []
  for i in range(a.shape[1]):
    column.append(round(np.average(a[:, i]), 3))
  return (column)

matrix_A = rndMatrix()
matrix_Avg_Row = avgRow(matrix_A)
matrix_Avg_Column = avgColumn(matrix_A)

print (matrix_A)
print ("Rows avg:", matrix_Avg_Row)
print ("Column avg:",matrix_Avg_Column)

[[-38 -72  76 -84 -53]
 [-11 -18 -27  54   7]]
Rows avg: [-34.2, 1.0]
Column avg: [-24.5, -45.0, 24.5, -15.0, -23.0]
